name: GNAT FSF snapshot publish
'on':
  schedule:
    - cron: "0 8 * * TUE" # run every Tuesday at 08:00 UTC
  workflow_dispatch: {}

jobs:
  dispatch_builds:
    name: "Publish new snapshot to index"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: snapshots-index
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: cd utils && python3 ./gen_gnat_snapshot_manifest.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
