name: Windows
on:
  #schedule:
  #  - cron:  '0 0 * * *'
  #push:
  pull_request:

jobs:
  gnat_gprbuild:
    name: GNAT Windows and gprbuild
    runs-on: windows-latest
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          git
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-gcc-ada
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core
    - name: Prepare msys2 build setup
      run: mkdir /d/aaa; mount D:/aaa /aaa ; ls /aaa; cd /aaa/ && git clone -b win-canadian https://github.com/alire-project/GNAT-FSF-builds

    - name: Build GNAT native
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup

    - name: Build GDB
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup

    - name: Package GNAT
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat,do_gh_release -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - name: Build GPRbuild
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup

    - name: Package GPRbuild
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gprbuild,do_gh_release -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - uses: actions/upload-artifact@v2
      with:
        name: anod-artifacts
        path: D:/aaa/GNAT-FSF-builds/out_artifacts/*
        retention-days: 1

    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: D:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5



  gnatcov:
    name: GNATcov
    needs: gnat_gprbuild
    runs-on: windows-latest
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          git
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-gcc-ada
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core
    - name: Prepare msys2 build setup
      run: mkdir /d/aaa; mount D:/aaa /aaa ; ls /aaa; cd /aaa/ && git clone -b win-canadian https://github.com/alire-project/GNAT-FSF-builds

    - uses: actions/download-artifact@v2
      with:
        name: anod-artifacts
        path: D:/aaa/GNAT-FSF-builds/in_artifacts/

    - name: Build GNATcov
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup

    - name: Package GNATcov
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatcov,do_gh_release -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: D:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5



  gnat_arm_elf:
    name: GNAT arm-elf-windows
    needs: gnat_gprbuild
    runs-on: windows-latest
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          git
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-gcc-ada
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core
    - name: Prepare msys2 build setup
      run: mkdir /d/aaa; mount D:/aaa /aaa ; ls /aaa; cd /aaa/ && git clone -b win-canadian https://github.com/alire-project/GNAT-FSF-builds

    - uses: actions/download-artifact@v2
      with:
        name: anod-artifacts
        path: D:/aaa/GNAT-FSF-builds/in_artifacts/

    - name: Build GNAT arm-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc -v --loglevel DEBUG --target=arm-elf --enable-cleanup

    - name: Build GDB arm-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb -v --loglevel DEBUG --target=arm-elf --enable-cleanup

    - name: Package GNAT arm-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat,do_gh_release --target=arm-elf -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: D:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5



  gnat_riscv64_elf:
    name: GNAT riscv64-elf-windows
    needs: gnat_gprbuild
    runs-on: windows-latest
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          git
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-gcc-ada
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core
    - name: Prepare msys2 build setup
      run: mkdir /d/aaa; mount D:/aaa /aaa ; ls /aaa; cd /aaa/ && git clone -b win-canadian https://github.com/alire-project/GNAT-FSF-builds

    - uses: actions/download-artifact@v2
      with:
        name: anod-artifacts
        path: D:/aaa/GNAT-FSF-builds/in_artifacts/


    - name: Build GNAT riscv64-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc -v --loglevel DEBUG --target=riscv64-elf --enable-cleanup

    - name: Build GDB riscv64-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb -v --loglevel DEBUG --target=riscv64-elf --enable-cleanup

    - name: Package GNAT riscv64-elf
      run: mount D:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat,do_gh_release --target=riscv64-elf -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: D:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
